#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Nishi Takuma
# SPDX-License-Identifier: BSD-3-Clause

import sys
ans = 0.0
for line in sys.stdin:
    try:
        ans += float(line)    #intは文字列を整数に（失敗すると例外発生）
    except:
        ans += float(line)
     
print(ans)
