name: test        
on: push          
jobs:             
  test:           
    runs-on: ubuntu-latest   #どの環境で動かすか
    steps:                   #手続きの記述
     - uses: actions/checkout@v3  #https://github.com/actions/checkoutのバージョン3を使用
     - name: All test             #このジョブの名前
       run: bash -xv ./test.bash  #テストのシェルスクリプトを走らせる
